version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
build:
  verbosity: minimal
before_build: 
  - nuget restore Extensions.sln
after_build:
  - nuget pack RuskinDantra.Extensions\RuskinDantra.Extensions.nuspec -Version %appveyor_build_version%
  - appveyor PushArtifact RuskinDantra.Extensions.%appveyor_build_version%.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: dwlwOZs2kUAq1SshxnIJIwQPm3h2kcA8KBXKQsVje3/9l1yvJ3aBXmCXh0HP5ZDo
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/